In [33]:

from scipy.stats import norm 
import scipy.stats as sts 
import numpy as np
import torch 
import importlib 
from torch.distributions import Normal  

import compute_prob
import init_params
import helper 

importlib.reload(helper)
importlib.reload(compute_prob)
importlib.reload(init_params)

<module 'init_params' from '/Users/caoanjie/Desktop/projects/model/model/GRANCH_python/init_params.py'>

In [36]:
a = init_params.granch_params(
    grid_mu_theta = torch.arange(0.01, 1.1, 0.1), 
    grid_sig_sq = torch.arange(0.01, 1.1, 0.1), 
    grid_y = torch.arange(0.01, 1.1, 0.1), 
    grid_epsilon = torch.arange(0.01, 1.1, 0.1), 
    hypothetical_obs_grid_n = 2, 
    mu_prior = 1,
    V_prior = 1, 
    alpha_prior = 1, 
    beta_prior = 1, 
    epsilons  = 0.01, 
    mu_epsilon = torch.tensor([0.01]), 
    sd_epsilon = torch.tensor([0.01]), 
    world_EIGs = 0.01,
    max_observation = 500
)


# set up the prior dfs 
a.add_meshed_grid()
a.add_lp_mu_sig_sq()
a.add_y_given_mu_sig_sq()
a.add_lp_epsilon()


print(a.lp_mu_sig_sq)
print(a.lp_mu_sig_sq.size())
print(a.y_given_mu_sig_sq)
print(a.y_given_mu_sig_sq.size())
print(a.lp_epsilon)
print(a.lp_epsilon.size())



tensor([-138.4110, -138.4110, -138.4110,  ...,   -1.9340,   -1.9340,
          -1.9340], dtype=torch.float64)
torch.Size([14641])
tensor([ 3.6862,  3.6862,  3.6862,  ..., -0.9289, -0.9289, -0.9289])
torch.Size([14641])
tensor([ 3.6862e+00, -4.6314e+01, -1.9631e+02,  ..., -3.1963e+03,
        -4.0463e+03, -4.9963e+03])
torch.Size([14641])
