In [ ]:
import numpy as np
import torch 
import pyro
import re
import pandas as pd

import importlib
import time
import pickle

from granch_utils import init_model_tensor, main_sim_tensor, lesioned_sim, compute_prob_tensor, init_params_tensor, num_stab_help, proxy_sim
#importlib.reload(granch_utils)
importlib.reload(num_stab_help)
importlib.reload(init_model_tensor)
importlib.reload(main_sim_tensor)
importlib.reload(lesioned_sim)

# Main TEST

In [407]:
importlib.reload(main_sim_tensor)
importlib.reload(lesioned_sim)
importlib.reload(init_params_tensor)
importlib.reload(compute_prob_tensor)
importlib.reload(proxy_sim)


device = 'cuda' if torch.cuda.is_available() else 'cpu'

BATCH_INFO = {
    "jitter_n": 1, 
    "total_batch_n": 1, 
    "jitter_mode": "sampling"
}

GRID_INFO = {
    "grid_mu_start": -4, "grid_mu_end": 4, "grid_mu_step": 5, 
    "grid_sigma_start": 0.001, "grid_sigma_end": 1.8, "grid_sigma_step": 5, 
    "grid_y_start": -4, "grid_y_end": 4, "grid_y_step": 5, 
    "grid_epsilon_start": 0.000001, "grid_epsilon_end": 1, "grid_epsilon_step": 5, 
    "hypothetical_obs_grid_n": 10
}


BATCH_GRID_INFO = num_stab_help.get_batch_grid(BATCH_INFO, GRID_INFO)

PRIOR_INFO = {
    "mu_prior": 1,  
    "V_prior": 1, 
    "alpha_prior": 3, 
    "beta_prior": 1, 
    "epsilon": 0.0001, "mu_epsilon":0.0001, "sd_epsilon": 0.0001, 
    "hypothetical_obs_grid_n": 2, 
    "world_EIGs": 3, "max_observation": 500
}

tensor_stimuli = num_stab_help.sample_spore_experiment(pair_each_stim = 1, n_feature=3)
print(tensor_stimuli)


tensor_model =  init_model_tensor.granch_model(PRIOR_INFO['max_observation'], tensor_stimuli[0])

params = init_params_tensor.granch_params(
                grid_mu =  BATCH_GRID_INFO["grid_mus"][0].to(device),
                grid_sigma = BATCH_GRID_INFO["grid_sigmas"][0].to(device),
                grid_y = BATCH_GRID_INFO["grid_ys"][0].to(device),
                grid_epsilon = BATCH_GRID_INFO["grid_epsilons"][0].to(device),
                hypothetical_obs_grid_n = PRIOR_INFO["hypothetical_obs_grid_n"], 
                mu_prior = PRIOR_INFO["mu_prior"],
                V_prior = PRIOR_INFO["V_prior"], 
                alpha_prior = PRIOR_INFO["alpha_prior"], 
                beta_prior = PRIOR_INFO["beta_prior"],
                epsilon  = PRIOR_INFO["epsilon"], 
                mu_epsilon = PRIOR_INFO["mu_epsilon"], 
                sd_epsilon = PRIOR_INFO["sd_epsilon"], 
                world_EIGs = PRIOR_INFO["world_EIGs"],
                max_observation = PRIOR_INFO["max_observation"], 
                forced_exposure_max= np.nan, 
                linking_hypothesis = "surprisal")
        
            # add the various different cached bits
params.add_meshed_grid()
params.add_lp_mu_sigma()
params.add_y_given_mu_sigma()
params.add_lp_epsilon()
params.add_priors()

if params.linking_hypothesis == "EIG": 
    res = main_sim_tensor.granch_main_simulation(params, tensor_model, tensor_stimuli[0])
else: 
    res, kl_df = proxy_sim.granch_proxy_sim(params, tensor_model, tensor_stimuli[0])

    res.to_csv("spores_res.csv")
    kl_df.to_csv("kl_df.csv")
#res = lesioned_sim.granch_no_learning_simulation(params, tensor_model, tensor_stimuli[0])
#res = lesioned_sim.granch_no_noise_simulation(params, tensor_model, tensor_stimuli[0])





[<granch_utils.init_model_tensor.granch_stimuli object at 0x2ba5af5e0>, <granch_utils.init_model_tensor.granch_stimuli object at 0x145646fe0>, <granch_utils.init_model_tensor.granch_stimuli object at 0x145647fa0>, <granch_utils.init_model_tensor.granch_stimuli object at 0x2ba317d90>, <granch_utils.init_model_tensor.granch_stimuli object at 0x143511210>, <granch_utils.init_model_tensor.granch_stimuli object at 0x2ba593490>, <granch_utils.init_model_tensor.granch_stimuli object at 0x14564f220>, <granch_utils.init_model_tensor.granch_stimuli object at 0x14564eef0>]
tensor([[[[[   -5.0543,   -68.8084,   -31.4665,  -810.5796,    -5.2213],
           [   -7.8044,  -114.1730,   -52.1510, -1341.8977,    -8.0949],
           [   -2.4021,   -25.0597,   -11.5187,  -298.1873,    -2.4499],
           [   -5.6292,   -78.2916,   -35.7904,  -921.6481,    -5.8220],
           [   -2.1829,   -21.4429,    -9.8695,  -255.8262,    -2.2208]],

          [[   -5.0543,   -68.8084,   -31.4665,  -810.5796,    -

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.16811950775756' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '-0.06858946269539051' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.04795514661366364' has dtype incompatible with int64, please explicitly cast to a compatible dt

tensor([[[[[   -5.0550,   -68.8197,   -31.4716,  -810.7121,    -5.2220],
           [   -7.8052,  -114.1876,   -52.1577, -1342.0681,    -8.0959],
           [   -2.4026,   -25.0666,   -11.5218,  -298.2678,    -2.4504],
           [   -5.6284,   -78.2795,   -35.7849,  -921.5068,    -5.8212],
           [   -2.1825,   -21.4365,    -9.8666,  -255.7516,    -2.2204]],

          [[   -5.0550,   -68.8197,   -31.4716,  -810.7121,    -5.2220],
           [   -7.8052,  -114.1876,   -52.1577, -1342.0681,    -8.0959],
           [   -2.4026,   -25.0666,   -11.5218,  -298.2678,    -2.4504],
           [   -5.6284,   -78.2795,   -35.7849,  -921.5068,    -5.8212],
           [   -2.1825,   -21.4365,    -9.8666,  -255.7516,    -2.2204]],

          [[   -5.0550,   -68.8197,   -31.4716,  -810.7121,    -5.2220],
           [   -7.8052,  -114.1876,   -52.1577, -1342.0681,    -8.0959],
           [   -2.4026,   -25.0666,   -11.5218,  -298.2678,    -2.4504],
           [   -5.6284,   -78.2795,   -35.7849,

TypeError: cannot unpack non-iterable granch_model object

In [372]:
res

stimulus_id  EIG Look_away   surprisal
0             0  NaN      True  299.957545
1             1  NaN      True   70.744366
2             2  NaN      True   70.744775
3             3  NaN      True   70.744405
4             4  NaN      True   70.744853
5             5  NaN      True   70.743610
6           NaN  NaN       NaN         NaN
7           NaN  NaN       NaN         NaN
8           NaN  NaN       NaN         NaN
9           NaN  NaN       NaN         NaN
10          NaN  NaN       NaN         NaN
11          NaN  NaN       NaN         NaN
12          NaN  NaN       NaN         NaN
13          NaN  NaN       NaN         NaN
14          NaN  NaN       NaN         NaN
15          NaN  NaN       NaN         NaN
16          NaN  NaN       NaN         NaN
17          NaN  NaN       NaN         NaN
18          NaN  NaN       NaN         NaN
19          NaN  NaN       NaN         NaN
20          NaN  NaN       NaN         NaN
21          NaN  NaN       NaN         NaN
22          NaN  NaN       NaN         NaN
23          NaN  NaN       NaN         NaN
24          NaN  NaN       NaN         NaN
25          NaN  NaN       NaN         NaN
26          NaN  NaN       NaN         NaN
27          NaN  NaN       NaN         NaN
28          NaN  NaN       NaN         NaN
29          NaN  NaN       NaN         NaN
30          NaN  NaN       NaN         NaN
31          NaN  NaN       NaN         NaN
32          NaN  NaN       NaN         NaN
33          NaN  NaN       NaN         NaN
34          NaN  NaN       NaN         NaN
35          NaN  NaN       NaN         NaN
36          NaN  NaN       NaN         NaN
37          NaN  NaN       NaN         NaN
38          NaN  NaN       NaN         NaN
39          NaN  NaN       NaN         NaN
40          NaN  NaN       NaN         NaN
41          NaN  NaN       NaN         NaN
42          NaN  NaN       NaN         NaN
43          NaN  NaN       NaN         NaN
44          NaN  NaN       NaN         NaN
45          NaN  NaN       NaN         NaN
46          NaN  NaN       NaN         NaN
47          NaN  NaN       NaN         NaN
48          NaN  NaN       NaN         NaN
49          NaN  NaN       NaN         NaN
50          NaN  NaN       NaN         NaN
51          NaN  NaN       NaN         NaN
52          NaN  NaN       NaN         NaN
53          NaN  NaN       NaN         NaN
54          NaN  NaN       NaN         NaN
55          NaN  NaN       NaN         NaN
56          NaN  NaN       NaN         NaN
57          NaN  NaN       NaN         NaN
58          NaN  NaN       NaN         NaN
59          NaN  NaN       NaN         NaN
60          NaN  NaN       NaN         NaN
61          NaN  NaN       NaN         NaN
62          NaN  NaN       NaN         NaN
63          NaN  NaN       NaN         NaN
64          NaN  NaN       NaN         NaN
65          NaN  NaN       NaN         NaN
66          NaN  NaN       NaN         NaN
67          NaN  NaN       NaN         NaN
68          NaN  NaN       NaN         NaN
69          NaN  NaN       NaN         NaN
70          NaN  NaN       NaN         NaN
71          NaN  NaN       NaN         NaN
72          NaN  NaN       NaN         NaN
73          NaN  NaN       NaN         NaN
74          NaN  NaN       NaN         NaN
75          NaN  NaN       NaN         NaN
76          NaN  NaN       NaN         NaN
77          NaN  NaN       NaN         NaN
78          NaN  NaN       NaN         NaN
79          NaN  NaN       NaN         NaN
80          NaN  NaN       NaN         NaN
81          NaN  NaN       NaN         NaN
82          NaN  NaN       NaN         NaN
83          NaN  NaN       NaN         NaN
84          NaN  NaN       NaN         NaN
85          NaN  NaN       NaN         NaN
86          NaN  NaN       NaN         NaN
87          NaN  NaN       NaN         NaN
88          NaN  NaN       NaN         NaN
89          NaN  NaN       NaN         NaN
90          NaN  NaN       NaN         NaN
91          NaN  NaN       NaN         NaN
92   

# Specific Grid Test

In [548]:
importlib.reload(main_sim_tensor)
importlib.reload(lesioned_sim)
importlib.reload(init_params_tensor)
importlib.reload(init_model_tensor)
importlib.reload(compute_prob_tensor)
importlib.reload(proxy_sim)
from torch.distributions import Normal, uniform


# test stimuli
test_stimuli = init_model_tensor.granch_stimuli(3, "BBBBBB")
test_stimuli.add_toy_example(0.3, 0.7)

# test grid  
grid_mu_distribution = uniform.Uniform(.2, .8)
grid_sigma_distribution = uniform.Uniform(.2, .8)
grid_y_distribution = uniform.Uniform(.2, .8)
grid_epsilon_distribution = uniform.Uniform(.2, .8)

# grid_mu = grid_mu_distribution.sample([2, ])
# grid_sigma = grid_sigma_distribution.sample([2, ])
# grid_y = grid_y_distribution.sample([2, ])
# grid_epsilon = grid_epsilon_distribution.sample([2, ])

grid_mu = torch.linspace(start = .2, end  = .8, steps = 5)
grid_sigma = torch.linspace(start = .2, end  = .8, steps = 5)
grid_y = torch.linspace(start = .2, end  = .8, steps = 5)
grid_epsilon = torch.linspace(start = .2, end  = .8, steps = 5)

# test prior
PRIOR_INFO = {
    "mu_prior": 1,  
    "V_prior": 1, 
    "alpha_prior": 1, 
    "beta_prior": 1, 
    "epsilon": 0.0001, "mu_epsilon":0.0001, "sd_epsilon": 0.0001, 
    "hypothetical_obs_grid_n": 2, 
    "world_EIGs": 0.001, "max_observation": 500
}


tensor_model =  init_model_tensor.granch_model(PRIOR_INFO['max_observation'], test_stimuli)

params = init_params_tensor.granch_params(
                grid_mu =  grid_mu,
                grid_sigma = grid_sigma,
                grid_y = grid_y, 
                grid_epsilon = grid_epsilon,
                hypothetical_obs_grid_n = 5, 
                mu_prior = PRIOR_INFO["mu_prior"],
                V_prior = PRIOR_INFO["V_prior"], 
                alpha_prior = PRIOR_INFO["alpha_prior"], 
                beta_prior = PRIOR_INFO["beta_prior"],
                epsilon  = PRIOR_INFO["epsilon"], 
                mu_epsilon = PRIOR_INFO["mu_epsilon"], 
                sd_epsilon = PRIOR_INFO["sd_epsilon"], 
                world_EIGs = PRIOR_INFO["world_EIGs"],
                max_observation = PRIOR_INFO["max_observation"], 
                forced_exposure_max= np.nan, 
                linking_hypothesis = "surprisal")
        
            # add the various different cached bits
params.add_meshed_grid()
params.add_lp_mu_sigma()
params.add_y_given_mu_sigma()
params.add_lp_epsilon()
params.add_priors()

if params.linking_hypothesis == "EIG": 
    res = main_sim_tensor.granch_main_simulation(params, tensor_model, test_stimuli)
else: 
    res = proxy_sim.granch_proxy_sim(params, tensor_model, test_stimuli)

res.behavior


/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.30011168122291565' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.29988840222358704' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.2999730110168457' has dtype incompatible with int64, please explicitly cast to a compatible d

tensor(-12.4852, dtype=torch.float64)
tensor(-13.2946, dtype=torch.float64)
tensor(-13.3100, dtype=torch.float64)
tensor(-13.3129, dtype=torch.float64)
tensor(-13.3140, dtype=torch.float64)
tensor(-13.3179, dtype=torch.float64)
tensor(-13.3183, dtype=torch.float64)
tensor(-13.3217, dtype=torch.float64)
tensor(-13.3198, dtype=torch.float64)
tensor(-13.3197, dtype=torch.float64)
tensor(-13.3204, dtype=torch.float64)
tensor(-13.3200, dtype=torch.float64)
tensor(-13.3205, dtype=torch.float64)
tensor(-13.3215, dtype=torch.float64)
tensor(-13.3208, dtype=torch.float64)
tensor(-13.3238, dtype=torch.float64)
tensor(-13.3208, dtype=torch.float64)
tensor(-13.3202, dtype=torch.float64)
tensor(-13.3217, dtype=torch.float64)
tensor(-13.3218, dtype=torch.float64)
tensor(-13.3205, dtype=torch.float64)
tensor(-13.3230, dtype=torch.float64)
tensor(-13.3198, dtype=torch.float64)
tensor(-13.3220, dtype=torch.float64)
tensor(-13.3225, dtype=torch.float64)
tensor(-13.3235, dtype=torch.float64)
tensor(-13.3

stimulus_id  EIG Look_away  surprisal            kl
0             0  NaN     False -12.485166  1.434026e-01
1             0  NaN     False -13.294644  8.591513e-04
2             0  NaN     False -13.309959  1.427475e-04
3             0  NaN     False -13.312906  3.384517e-05
4             0  NaN     False -13.314026  7.788265e-06
5             0  NaN     False -13.317922  1.050467e-06
6             0  NaN     False -13.318296  2.218626e-07
7             0  NaN     False -13.321696  1.064257e-06
8             0  NaN     False -13.319807  2.046861e-06
9             0  NaN     False -13.319726  2.779853e-06
10            0  NaN     False -13.320357  3.189787e-06
11            0  NaN     False -13.319978  3.317061e-06
12            0  NaN     False -13.320496  3.268161e-06
13            0  NaN     False -13.321542  3.107795e-06
14            0  NaN     False -13.320846  2.864508e-06
15            0  NaN     False -13.323758  2.624803e-06
16            0  NaN     False -13.320789  2.327022e-06
17            0  NaN     False -13.320177  2.059988e-06
18            0  NaN     False -13.321705  1.821922e-06
19            0  NaN     False -13.321795  1.593146e-06
20            0  NaN     False -13.320496  1.379804e-06
21            0  NaN     False -13.323023  1.204185e-06
22            0  NaN     False -13.319814  1.026963e-06
23            0  NaN     False -13.321985  8.890752e-07
24            0  NaN     False -13.322513  7.624913e-07
25            0  NaN     False -13.323486  6.531277e-07
26            0  NaN     False -13.321116  5.518661e-07
27            0  NaN     False -13.321098  4.689698e-07
28            0  NaN     False -13.321372  3.979274e-07
29            0  NaN     False -13.320188  3.355680e-07
30            0  NaN     False -13.321715  2.852368e-07
31            0  NaN     False -13.320493  2.395072e-07
32            0  NaN     False -13.321240  2.019657e-07
33            0  NaN     False -13.322435  1.708532e-07
34            0  NaN     False -13.321296  1.427506e-07
35            0  NaN     False -13.322654  1.205475e-07
36            0  NaN     False -13.321336  1.005439e-07
37            0  NaN     False -13.320132  8.383073e-08
38            0  NaN     False -13.321173  7.044960e-08
39            0  NaN     False -13.320864  5.856151e-08
40            0  NaN     False -13.320646  4.912253e-08
41            0  NaN     False -13.321052  4.117148e-08
42            0  NaN     False -13.322080  3.451047e-08
43            0  NaN     False -13.323976  2.859245e-08
44            0  NaN     False -13.323466  2.409354e-08
45            0  NaN     False -13.322071  1.967296e-08
46            0  NaN     False -13.320065  1.649242e-08
47            0  NaN     False -13.320560  1.370354e-08
48            0  NaN     False -13.322894  1.151746e-08
49            0  NaN     False -13.319752  9.396095e-09
50            0  NaN     False -13.321603  7.904992e-09
51            0  NaN     False -13.318384  6.349722e-09
52            0  NaN     False -13.322370  5.733910e-09
53            0  NaN     False -13.320688  4.517677e-09
54            0  NaN     False -13.319515  3.726023e-09
55            0  NaN     False -13.321827  2.929471e-09
56            0  NaN     False -13.320227  2.654053e-09
57            0  NaN     False -13.322259  2.219464e-09
58            0  NaN     False -13.321639  1.795804e-09
59            0  NaN     False -13.321061  1.542087e-09
60            0  NaN     False -13.322987  1.198951e-09
61            0  NaN     False -13.321046  9.556352e-10
62            0  NaN     False -13.320137  9.847998e-10
63            0  NaN     False -13.319971  7.105811e-10
64            0  NaN     False -13.323654  6.447829e-10
65            0  NaN     False -13.319392  5.771165e-10
66            0  NaN     False -13.320244  2.509283e-10
67            0  NaN     False -13.321155  2.966170e-10
68            0  NaN     False -13.321593  4.198927e-10
69            0  NaN     False -13.318097 -6.263895e-11
70            0  NaN     Fal

# Visualizing random grid KL (500)

In [544]:
importlib.reload(main_sim_tensor)
importlib.reload(lesioned_sim)
importlib.reload(init_params_tensor)
importlib.reload(compute_prob_tensor)
importlib.reload(proxy_sim)


def run_random_grid_and_visualize_kl():


    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    BATCH_INFO = {
        "jitter_n": 1, 
        "total_batch_n": 1, 
        "jitter_mode": "sampling"
    }

    GRID_INFO = {
       "grid_mu_start": -4, "grid_mu_end": 4, "grid_mu_step": 5, 
       "grid_sigma_start": 0.001, "grid_sigma_end": 1.8, "grid_sigma_step": 5, 
       "grid_y_start": -4, "grid_y_end": 4, "grid_y_step": 5, 
       "grid_epsilon_start": 0.000001, "grid_epsilon_end": 1, "grid_epsilon_step": 5, 
       "hypothetical_obs_grid_n": 10
    }


#    GRID_INFO = {
#        "grid_mu_start": .2, "grid_mu_end": .8, "grid_mu_step": 5, 
#        "grid_sigma_start": .2, "grid_sigma_end": .8, "grid_sigma_step": 5, 
#        "grid_y_start":.2, "grid_y_end": 8, "grid_y_step": 5, 
#        "grid_epsilon_start": .2, "grid_epsilon_end": .8, "grid_epsilon_step": 5, 
#        "hypothetical_obs_grid_n": 10
#    }



    BATCH_GRID_INFO = num_stab_help.get_batch_grid(BATCH_INFO, GRID_INFO)

    PRIOR_INFO = {
        "mu_prior": 1,  
        "V_prior": 1, 
        "alpha_prior": 3, 
        "beta_prior": 1, 
        "epsilon": 0.0001, "mu_epsilon":0.0001, "sd_epsilon": 0.0001, 
        "hypothetical_obs_grid_n": 2, 
        "world_EIGs": 0.01, "max_observation": 500
    }


    test_stimuli = init_model_tensor.granch_stimuli(3, "BBBBBD")
    test_stimuli.add_toy_example(0.3, 0.7)
    



    tensor_model =  init_model_tensor.granch_model(PRIOR_INFO['max_observation'], test_stimuli)

    params = init_params_tensor.granch_params(
                    grid_mu =  BATCH_GRID_INFO["grid_mus"][0].to(device),
                    grid_sigma = BATCH_GRID_INFO["grid_sigmas"][0].to(device),
                    grid_y = BATCH_GRID_INFO["grid_ys"][0].to(device),
                    grid_epsilon = BATCH_GRID_INFO["grid_epsilons"][0].to(device),
                    hypothetical_obs_grid_n = PRIOR_INFO["hypothetical_obs_grid_n"], 
                    mu_prior = PRIOR_INFO["mu_prior"],
                    V_prior = PRIOR_INFO["V_prior"], 
                    alpha_prior = PRIOR_INFO["alpha_prior"], 
                    beta_prior = PRIOR_INFO["beta_prior"],
                    epsilon  = PRIOR_INFO["epsilon"], 
                    mu_epsilon = PRIOR_INFO["mu_epsilon"], 
                    sd_epsilon = PRIOR_INFO["sd_epsilon"], 
                    world_EIGs = PRIOR_INFO["world_EIGs"],
                    max_observation = PRIOR_INFO["max_observation"], 
                    forced_exposure_max= np.nan, 
                    linking_hypothesis = "surprisal")
            
                # add the various different cached bits
    params.add_meshed_grid()
    params.add_lp_mu_sigma()
    params.add_y_given_mu_sigma()
    params.add_lp_epsilon()
    params.add_priors()

    if params.linking_hypothesis == "EIG": 
        res = main_sim_tensor.granch_main_simulation(params, tensor_model, test_stimuli)
    else: 
        res = proxy_sim.granch_proxy_sim(params, tensor_model, test_stimuli)

    return res


#res = lesioned_sim.granch_no_learning_simulation(params, tensor_model, tensor_stimuli[0])
#res = lesioned_sim.granch_no_noise_simulation(params, tensor_model, tensor_stimuli[0])



# try it out 5 eims
res_list = []
#kl_df_list = []
for i in range(2000): 
    print(i)
    res= (run_random_grid_and_visualize_kl()).behavior
    res["id"] = i
    res_list.append(res)
    #kl_df_list.append(kl_df)

main_res = pd.concat(res_list)
#kl_df_res = pd.concat(kl_df_list)

main_res.to_csv("diagnostics/sim_res.csv")
#main_res.dropna()
#print(res.behavior)
#main_sim_tensor.granch_main_simulation(PRIOR_INFO, tensor_model, tensor_stimuli)



0
tensor(-4.3281e-08, dtype=torch.float64)
tensor(-4.3281e-08, dtype=torch.float64)
tensor(-4.3281e-08, dtype=torch.float64)
tensor(-4.3281e-08, dtype=torch.float64)
tensor(-4.3281e-08, dtype=torch.float64)
tensor(-4.3281e-08, dtype=torch.float64)
1
tensor(-2.0384, dtype=torch.float64)
tensor(-2.4123, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4123, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4119, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.29983359575271606' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.30007535219192505' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.3001207709312439' has dtype incompatible with int64, please explicitly cast to a compatible d

tensor(-2.4123, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4124, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4123, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4120, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4121, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
tensor(-2.4122, dtype=torch.float64)
t

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.30001121759414673' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.30006733536720276' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.29989752173423767' has dtype incompatible with int64, please explicitly cast to a compatible 

tensor(-8.1743, dtype=torch.float64)
tensor(-8.1819, dtype=torch.float64)
tensor(-8.1764, dtype=torch.float64)
tensor(-8.1757, dtype=torch.float64)
tensor(-8.1745, dtype=torch.float64)
tensor(-8.1786, dtype=torch.float64)
tensor(-8.1840, dtype=torch.float64)
tensor(-8.1849, dtype=torch.float64)
tensor(-8.1729, dtype=torch.float64)
tensor(-8.1730, dtype=torch.float64)
tensor(-8.1743, dtype=torch.float64)
tensor(-8.1754, dtype=torch.float64)
tensor(-8.1859, dtype=torch.float64)
tensor(-8.1829, dtype=torch.float64)
tensor(-8.1746, dtype=torch.float64)
tensor(-8.1708, dtype=torch.float64)
tensor(-8.1719, dtype=torch.float64)
tensor(-8.1770, dtype=torch.float64)
tensor(-8.1740, dtype=torch.float64)
tensor(-8.1790, dtype=torch.float64)
tensor(-8.1699, dtype=torch.float64)
tensor(-8.1716, dtype=torch.float64)
tensor(-8.1686, dtype=torch.float64)
tensor(-8.1730, dtype=torch.float64)
tensor(-8.1767, dtype=torch.float64)
tensor(-8.1738, dtype=torch.float64)
tensor(-8.1680, dtype=torch.float64)
t

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.30001503229141235' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.2998630106449127' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.2998775243759155' has dtype incompatible with int64, please explicitly cast to a compatible dt

tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0165, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0165, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
tensor(-0.0164, dtype=torch.float64)
t

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.30014482140541077' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.29999789595603943' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.2999219596385956' has dtype incompatible with int64, please explicitly cast to a compatible d

tensor(-5.0179, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0179, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
tensor(-5.0180, dtype=torch.float64)
t

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.30005332827568054' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.30007392168045044' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.3000729978084564' has dtype incompatible with int64, please explicitly cast to a compatible d

tensor(-0.6492, dtype=torch.float64)
tensor(-0.6490, dtype=torch.float64)
tensor(-0.6492, dtype=torch.float64)
tensor(-0.6492, dtype=torch.float64)
tensor(-0.6492, dtype=torch.float64)
tensor(-0.6488, dtype=torch.float64)
tensor(-0.6493, dtype=torch.float64)
tensor(-0.6491, dtype=torch.float64)
tensor(-0.6493, dtype=torch.float64)
tensor(-0.6489, dtype=torch.float64)
tensor(-0.6494, dtype=torch.float64)
tensor(-0.6494, dtype=torch.float64)
tensor(-0.6490, dtype=torch.float64)
tensor(-0.6497, dtype=torch.float64)
tensor(-0.6488, dtype=torch.float64)
tensor(-0.6491, dtype=torch.float64)
tensor(-0.6493, dtype=torch.float64)
tensor(-0.6491, dtype=torch.float64)
tensor(-0.6489, dtype=torch.float64)
tensor(-0.6492, dtype=torch.float64)
tensor(-0.6494, dtype=torch.float64)
tensor(-0.6491, dtype=torch.float64)
tensor(-0.6492, dtype=torch.float64)
tensor(-0.6494, dtype=torch.float64)
tensor(-0.6492, dtype=torch.float64)
tensor(-0.6494, dtype=torch.float64)
tensor(-0.6495, dtype=torch.float64)
t

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.2999093532562256' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.3000396192073822' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

/Users/caoanjie/Desktop/projects/looking_time_models/03_pyGRANCH_multi/granch_utils/init_model_tensor.py:302: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.29998478293418884' has dtype incompatible with int64, please explicitly cast to a compatible dt

tensor(-1.1465, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1466, dtype=torch.float64)
tensor(-1.1466, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1466, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1466, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1466, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
tensor(-1.1464, dtype=torch.float64)
tensor(-1.1465, dtype=torch.float64)
t

KeyboardInterrupt: 

In [ ]:
import plotly.subplots as sp
import plotly.graph_objects as go
import pandas as pd
import plotly.express as px

df = main_res

# Get unique categories
id = df['id'].unique()
# Create a subplot grid
fig = sp.make_subplots(rows=len(id), cols=1, subplot_titles=["1", "2", "3", "4", "5"])

# Populate each subplot
for i, idx in enumerate(id):
    subset = df[df['id'] == idx]
    print(subset)
    single_fig = px.line(df, x='t', y=['kl1', 'kl2'], labels={'kl1': 'kl1', 'kl2': 'kl2'}, markers=True)
    single_fig.update_layout(
    xaxis_title='t',
    yaxis_title='Value',
    legend_title='Legend',
    )


    for trace in single_fig.data:
        fig.add_trace(trace, row=i + 1, col=1)

# Update subplot layout (optional)
fig.update_layout(
    title='Faceted Line Plots',
    showlegend=True,
    height=600,
    width=400,
)

# Show the plot
fig.show()


In [ ]:
import pandas as pd
import plotly.express as px



df = res.iloc[:50]

# Create a line plot using Plotly Express
fig = px.line(df, x='t', y=['kl1', 'kl2'], labels={'kl1': 'kl1', 'kl2': 'kl2'}, markers=True)

# Customize the layout (optional)
fig.update_layout(
    title='Line Plot with Plotly',
    xaxis_title='t',
    yaxis_title='Value',
    legend_title='Legend',
)

# Show the plot
fig.show()


# Toy Example Test 

In [179]:
importlib.reload(init_model_tensor)
importlib.reload(lesioned_sim)
importlib.reload(init_params_tensor)
importlib.reload(compute_prob_tensor)
importlib.reload(main_sim_tensor)
importlib.reload(proxy_sim)

test_stimuli = init_model_tensor.granch_stimuli(3, "BBBBBD")
test_stimuli.add_toy_example(0.3, 0.7)

tensor_model =  init_model_tensor.granch_model(PRIOR_INFO['max_observation'], tensor_stimuli[0])

params = init_params_tensor.granch_params(
                grid_mu =  BATCH_GRID_INFO["grid_mus"][0].to(device),
                grid_sigma = BATCH_GRID_INFO["grid_sigmas"][0].to(device),
                grid_y = BATCH_GRID_INFO["grid_ys"][0].to(device),
                grid_epsilon = BATCH_GRID_INFO["grid_epsilons"][0].to(device),
                hypothetical_obs_grid_n = PRIOR_INFO["hypothetical_obs_grid_n"], 
                mu_prior = PRIOR_INFO["mu_prior"],
                V_prior = PRIOR_INFO["V_prior"], 
                alpha_prior = PRIOR_INFO["alpha_prior"], 
                beta_prior = PRIOR_INFO["beta_prior"],
                epsilon  = PRIOR_INFO["epsilon"], 
                mu_epsilon = PRIOR_INFO["mu_epsilon"], 
                sd_epsilon = PRIOR_INFO["sd_epsilon"], 
                world_EIGs = 3,
                #world_EIGs = PRIOR_INFO["world_EIGs"],
                #max_observation = PRIOR_INFO["max_observation"], 
                max_observation = 500,
                forced_exposure_max= np.nan, 
                linking_hypothesis= "surprisal")
        
            # add the various different cached bits
params.add_meshed_grid()
params.add_lp_mu_sigma()
params.add_y_given_mu_sigma()
params.add_lp_epsilon()
params.add_priors()

pd.set_option('display.max_rows', None)

#res = main_sim_tensor.granch_main_simulation(params, tensor_model, test_stimuli)
res = proxy_sim.granch_proxy_sim(params, tensor_model, test_stimuli)
#res.behavior

res.behavior

NameError: name 'tensor_stimuli' is not defined

In [ ]:
res.behavior

In [303]:
import torch.nn.functional as F

new_post = torch.tensor([[[[ 4.1338e-01, 9.9999e-321],
          [ 3.6698e-02, 9.9999e-321]],

         [[ 4.8830e-01, 9.9999e-321],
          [ 6.1620e-02, 9.9999e-321]]],


        [[[ 4.1338e-01, 9.9999e-321],
          [ 3.6698e-02, 9.9999e-321]],

         [[ 4.8830e-01, 9.9999e-321],
          [ 6.1619e-02, 9.9999e-321]]],


        [[[ 4.1338e-01, 9.9999e-321],
          [ 3.6698e-02, 9.9999e-321]],

         [[ 4.8830e-01, 9.9999e-321],
          [ 6.1620e-02, 9.9999e-321]]]], dtype=torch.float64)

paded_prev_post = torch.tensor([[[[1.0000e+00, 1.0000e-31],
          [1.3534e-01, 1.0000e-31]],

         [[1.0000e+00, 1.0000e-31],
          [1.3534e-01, 1.0000e-31]]],


        [[[1.0000e+00, 1.0000e-31],
          [1.3534e-01, 1.0000e-31]],

         [[1.0000e+00, 1.0000e-31],
          [1.3534e-01, 1.0000e-31]]],


        [[[1.0000e+00, 1.0000e-31],
          [1.3534e-01, 1.0000e-31]],

         [[1.0000e+00, 1.0000e-31],
          [1.3534e-01, 1.0000e-31]]]])

#print(new_post/paded_prev_post)
#print(torch.log(new_post/paded_prev_post))

KL1 = torch.sum(torch.mul(new_post,
                         torch.log(new_post/paded_prev_post)), dim = (1, 2, 3))

KL2 = F.kl_div(torch.log(paded_prev_post),new_post, reduction = "none").sum(dim = (1, 2, 3))

print(KL1)
print(KL2)

print(new_post.sum())
print(paded_prev_post.sum(dim = (1, 2, 3)))
print(new_post < paded_prev_post)

print(torch.log(new_post/paded_prev_post))

tensor([-0.8116, -0.8116, -0.8116], dtype=torch.float64)
tensor([-0.8116, -0.8116, -0.8116], dtype=torch.float64)
tensor(3.0000, dtype=torch.float64)
tensor([2.2707, 2.2707, 2.2707])
tensor([[[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]],


        [[[True, True],
          [True, True]],

         [[True, True],
          [True, True]]]])
tensor([[[[  -0.8834, -665.4471],
          [  -1.3051, -665.4471]],

         [[  -0.7168, -665.4471],
          [  -0.7868, -665.4471]]],


        [[[  -0.8834, -665.4471],
          [  -1.3051, -665.4471]],

         [[  -0.7168, -665.4471],
          [  -0.7868, -665.4471]]],


        [[[  -0.8834, -665.4471],
          [  -1.3051, -665.4471]],

         [[  -0.7168, -665.4471],
          [  -0.7868, -665.4471]]]], dtype=torch.float64)


# Test KL overflow

In [241]:

A = torch.tensor([9.9999e-321,  2.4348e-01])
B = torch.tensor([1.0000e-31, 3.6788e-01])
        
A_cast_first = torch.tensor([9.9999e-321,  2.4348e-01], dtype=torch.float64)
B_cast_first = torch.tensor([1.0000e-31, 3.6788e-01], dtype=torch.float64)  

A_cast_later = A.to(torch.float64)
B_cast_later = B.to(torch.float64)


mask = A_cast_later < 1e-10
A_cast_later[mask] = 1e-10 
mask = B_cast_later < 1e-10
B_cast_later[mask] = 1e-10


KL1 = torch.sum(torch.mul(A,torch.log(A/B)))
KL2 = torch.sum(torch.mul(A_cast_later,torch.log(A_cast_later/B_cast_later)))
KL3 =  torch.sum(torch.mul(A_cast_first,torch.log(A_cast_first/B_cast_first)))

print(KL1)
print(KL2)
print(KL3)

tensor(nan)
tensor(-0.1005, dtype=torch.float64)
tensor(-0.1005, dtype=torch.float64)


In [168]:
A = torch.tensor([9.9999e-321])
B = A.to(torch.float64)
print(A)
print(B)
print(B.dtype)

tensor([0.])
tensor([0.], dtype=torch.float64)
torch.float64


In [124]:
pred = torch.tensor([[0.2, 0.8]])
target = torch.tensor([[0.1, 0.9]])

kl2_a = F.kl_div(pred, target, reduction='sum', log_target=False)

kl2_b = F.kl_div(target, pred, reduction='sum', log_target=True)

KL1 = torch.sum(torch.mul(new_post, torch.log(new_post/paded_prev_post)), dim = 0)

print(kl2_a)
print(kl2_b)

print(torch.sum(torch.exp(target) * (target - pred)))


tensor(-1.0651)
tensor(-0.1004)
tensor(0.1354)
